name: Test Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby 3.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Build and run test
        env:
          PDL_API_KEY: ${{secrets.PDL_API_KEY}}
        run: |
          gem install bundler
          bundle install
          gem build *.gemspec
          gem install *.gem
          rake spec
