name: Test Package

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Build and run test
        env:
          PDL_API_KEY: ${{secrets.PDL_API_KEY}}
        run: |
          bundle install
          gem build peopledatalabs.gemspec
          gem install ./peopledatalabs-1.0.0.gem
          rake spec
